[project]
name = 'Blockchain-Based-Liquidity-Provision-Optimization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.capital-allocation]
path = 'contracts/capital-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.pool-analysis]
path = 'contracts/pool-analysis.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
